### ISSUE TITLE
Adicionar dados

### ISSUE THREAD

**Issue by fellix** [gurusc/gurusc-old-site#2]
Cara seria legal por o endereço bem certo na página, não tenho certeza de qual é pra por :P

e também adicionar o link do hotel http://www.hotelvalerim.com.br/ dica o @MarceloCajueiro

**Comment by fnmunhoz** [comment]
Legal, será o próximo passo!

**Comment by fnmunhoz** [comment]
Done

**Comment by fellix** [comment]
Show de bola :)
